version: 2

jobs:
  build:
    machine: true
    working_directory: /home/circleci/.go_workspace/src/github.com/go-kit/kit
    environment:
      ETCD_ADDR: http://localhost:2379
      CONSUL_ADDR: localhost:8500
      ZK_ADDR: localhost:2181
      EUREKA_ADDR: http://localhost:8761/eureka     
    steps:
      - checkout
      - run: docker-compose -f docker-compose-integration.yml up -d --force-recreate
      - run: go get -t github.com/go-kit/kit/...
      - run: go test -v -race -tags integration github.com/go-kit/kit/...
  build-go1.11-modules:
    docker:
      - image: circleci/golang:1.11-rc
    working_directory: ~/go
    environment:
      ETCD_ADDR: http://localhost:2379
      CONSUL_ADDR: localhost:8500
      ZK_ADDR: localhost:2181
      EUREKA_ADDR: http://localhost:8761/eureka     
    steps:
      - checkout
      - run: go test -v -race -tags integration github.com/go-kit/kit/...
workflows:
  version: 2
  test-both:
    jobs:
      - build
      - build-go1.11-modules
